"""link_id and ip_address in clics now has index

Revision ID: 7f555636bd8a
Revises: 7d40c8b7fc85
Create Date: 2025-02-07 17:26:20.500937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f555636bd8a'
down_revision: Union[str, None] = '7d40c8b7fc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clicks_ip_address'), 'clicks', ['ip_address'], unique=False)
    op.create_index(op.f('ix_clicks_link_id'), 'clicks', ['link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_link_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_ip_address'), table_name='clicks')
    # ### end Alembic commands ###
