services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app1-backend
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: uvicorn app.main:app --host 0.0.0.0
    networks:
      - app1-network
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app1-network

  frontend:
    image: nginx:latest
    container_name: app1-frontend
    restart: always
    volumes:
      - ./app/static:/usr/share/nginx/html
    ports:
      - 8081:80
    networks:
      - app1-network
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local

networks:
  app1-network:
    external: true